---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drums-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drums-client
  template:
    metadata:
      labels:
        app: drums-client
    spec:
      containers:
        - name: drums-client-container
          image: docker.io/blindmuaddib/drums-endpoint:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 25941
          env:
            - name: DRUMS_CPU_WORKERS
              value: "2"
          resources:
            requests:
              cpu: "4"
              memory: "4Gi"
            limits:
              cpu: "6"
              memory: "8Gi"
          volumeMounts:
            - name: shared-data
              mountPath: /shared-data/separator_output
              subPath: separator_output
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc


