---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translator-worker
  template:
    metadata:
      labels:
        app: translator-worker
    spec:
      containers:
      - name: worker
        image: blindmuaddib/music-translator:latest
        command: ["python", "worker.py"]
        env:
          - name: REDIS_HOST
            value: "redis-service"
          - name: REDIS_PORT
            value: "6379"
        volumeMounts:
          - name: shared-data-volume
            mountPath: /shared-data
        resources:
          limits:
            memory: "8Gi"
            cpu: "2"
          requests:
            memory: "2Gi"
            cpu: "500m"
      volumes:
        - name: shared-data-volume
          persistentVolumeClaim:
            claimName: shared-data-pvc
