# Use a multi-architecture base image
FROM python:3.9-slim

#Set the working directory in the container
WORKDIR /app

# Install system dependencies
COPY requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application files
COPY . .

# Command to run the app
CMD ["python", "app.py"]
