apiVersion: apps/v1
kind: Deployment
metadata:
  name: spleeter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spleeter-wrapper
  template:
    metadata:
      labels:
        app: spleeter-wrapper
    spec:
      containers:
        - name: spleeter-wrapper-container
          image: spleeter-wrapper:latest
          ports:
            - containerPort: 24725
